apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: uploader
  name: uploader
spec:
  output:
    to:
      kind: ImageStreamTag
      name: uploader:latest
  source:
    git:
      uri: https://github.com/chmouel/openshift-django-uploader/
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
