apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uploader
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
      deploymentconfig: uploader
  template:
    metadata:
      labels:
        app: uploader
        deploymentconfig: uploader
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: my-nginx-conf
        - mountPath: /fileuploads
          name: staticfiles
      - env:
        - name: APP_MODULE
          value: osinstall.wsgi
        - name: DISABLE_MIGRATE
          value: "true"
        - name: SECRET_KEY
          value: %SECRET_KEY%
        command: ["gunicorn", "osinstall.wsgi", "--bind=0.0.0.0:9000", "--access-logfile=-", "--reload"]
        image: %IMAGE%
        name: uploader
        volumeMounts:
        - mountPath: /opt/app-root/src/fileuploads
          name: staticfiles
      volumes:
      - configMap:
          defaultMode: 420
          name: my-nginx-conf
        name: my-nginx-conf
      - emptyDir: {}
        name: staticfiles
